### ISSUE TITLE
[Feature] 添加部署指导文档

### ISSUE THREAD

**Issue by li-guohao** [ikaros-dev/ikaros#118]
### Search before asking

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### Description

添加部署指导文档，要求有 docker run 部署 和 docker compose部署两种文档，在目录 `docs/deploy/` 下

### TODO LIST
- [x] Docker Run 部署文档
- [ ] Docker Compose 部署文档

### Are you willing to submit a PR?

- [X] 是的我想要提交个PR!

### Related Issues
- #115

### Related pull requests
- #116 
- #117
- #119
